# -*- coding: utf-8 -*-
"""mental_bert.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jZymamxorGl5rtN62MD7FR6IED_Jp36b
"""

from google.colab import drive
drive.mount('/content/drive')

import re
import string
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split

input_csv = "/content/drive/MyDrive/Thesis/Code/text_classifier/data/df_concat.csv"
df = pd.read_csv(input_csv )
df = df.sample(frac=1).reset_index(drop=True)

def clean_text(text):

    # Remove URLs https://www.
    ulr_pattern = re.compile(r'https?://\S+|www\.\S+')
    text = ulr_pattern.sub(r'', text)

    # Remove HTML tags
    html_pattern = re.compile('<.*?>')
    text = html_pattern.sub(r'', text)
    # remove puncs and digits
    replace_chars = list(string.punctuation + string.digits)
    for char in replace_chars:
        text = text.replace(char, " ")

    # remove emoji
    emoji_pattern = re.compile("["
        u"\U0001F600-\U0001F64F"  # emoticons
        u"\U0001F300-\U0001F5FF"  # symbols & pictographs
        u"\U0001F680-\U0001F6FF"  # transport & map symbols
        u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
        u"\U0001F1F2-\U0001F1F4"  # Macau flag
        u"\U0001F1E6-\U0001F1FF"  # flags
        u"\U0001F600-\U0001F64F"
        u"\U00002702-\U000027B0"
        u"\U000024C2-\U0001F251"
        u"\U0001f926-\U0001f937"
        u"\U0001F1F2"
        u"\U0001F1F4"
        u"\U0001F620"
        u"\u200d"
        u"\u2640-\u2642"
        "]+", flags=re.UNICODE)
    text = emoji_pattern.sub(r" ", text)

    # normalize whitespace
    text = " ".join(text.split())

    # lowercasing
    text = text.lower()
    return text

def handle_label(text):
  text = text.split(".")[-1].lower()
  return str(text)

df.head()

texts = df["prompt"].astype(str).tolist()
labels = df["category"].tolist()
train_texts, val_texts, train_labels, val_labels = train_test_split(
    texts,
    labels,
    test_size=0.2,
    random_state=42,
    stratify=labels
)

train_df = pd.DataFrame({"text": train_texts, "label": train_labels})
val_df = pd.DataFrame({"text": val_texts, "label": val_labels})

train_df['processed_text'] = train_df['text'].apply(clean_text)
train_df['label'] = train_df['label'].apply(handle_label)
labels = train_df['label'].unique()
label_encoder = OneHotEncoder(sparse_output=False)
label_encoder.fit(labels.reshape(-1, 1))
train_encoded_labels = label_encoder.fit_transform(train_df[['label']])
labels = label_encoder.categories_
train_df['label_code'] = train_encoded_labels.argmax(axis=1)




val_df['processed_text'] = val_df['text'].apply(clean_text)
val_df['label'] = val_df['label'].apply(handle_label)
val_encoded_labels = label_encoder.transform(val_df[['label']])
val_df['label_code'] = val_encoded_labels.argmax(axis=1)

train_df.head()

from transformers import AutoModelForSequenceClassification, AutoTokenizer, AutoModel
import torch
import os
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
# Load the tokenizer and the model
model_name = "mental/mental-bert-base-uncased"
# model_name = 'bert-base-uncased'
def load_model(model_name):
    tokenizer = AutoTokenizer.from_pretrained(model_name,clean_up_tokenization_spaces = True, device_map=device)
    model = AutoModelForSequenceClassification.from_pretrained(model_name, device_map=device)

    model_dir= model_name
    _ = model.save_pretrained(model_dir)
    _ = tokenizer.save_pretrained(model_dir)
    return model, tokenizer
# model, tokenizer = load_model(model_name)

import torch
from torch.utils.data import DataLoader, Dataset
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained(model_name)

class TextDataset(Dataset):
    def __init__(self, X, y, tokenizer, max_length=256):
        self.texts = X  # Văn bản đầu vào
        self.labels = y  # Nhãn đầu ra
        self.tokenizer = tokenizer  # Tokenizer để mã hóa văn bản
        self.max_length = max_length  # Độ dài tối đa của văn bản

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, idx):
        text = str(self.texts.iloc[idx])  # Lấy văn bản tại chỉ số idx
        label = torch.tensor(self.labels[idx], dtype=torch.long)  # Chuyển nhãn thành tensor

        # Token hóa văn bản
        encoding = self.tokenizer.encode_plus(
            text,                      # Văn bản cần token hóa
            add_special_tokens=True,   # Thêm special tokens như [CLS], [SEP] trong BERT
            max_length=self.max_length, # Đặt độ dài tối đa cho các chuỗi
            padding='max_length',      # Padding văn bản để có cùng độ dài
            truncation=True,           # Cắt văn bản nếu quá dài
            return_tensors='pt',       # Trả về dạng PyTorch tensor
        )

        # Trả về input_ids, attention_mask và nhãn
        return {
            'input_ids': encoding['input_ids'].squeeze(),  # Xóa bớt chiều (batch dimension)
            'attention_mask': encoding['attention_mask'].squeeze(),  # Attention mask
            'labels': label
        }


# Tạo DataLoader cho train, val, và test
train_dataset = TextDataset(train_df['text'], train_df['label_code'] , tokenizer)
val_dataset = TextDataset(val_df['text'], val_df['label_code'], tokenizer)

train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=64, shuffle=False)

sample = next(iter(train_loader))
print(sample['input_ids'].shape)
print(sample['attention_mask'].shape)
print(sample['labels'].shape)
print(sample['labels'])

sample = next(iter(val_loader))
print(sample['input_ids'].shape)
print(sample['attention_mask'].shape)
print(sample['labels'].shape)
print(sample['labels'])

# num_labels = 5
# model = AutoModelForSequenceClassification.from_pretrained("mental/mental-bert-base-uncased", num_labels=num_labels)

def evaluate(model, val_loader, device):
    model.eval()
    val_loss = 0.0
    val_acc_list = []

    with torch.no_grad():
        for batch in val_loader:
            input_ids = batch['input_ids'].to(device)
            attention_mask = batch['attention_mask'].to(device)
            labels = batch['labels'].to(device)

            outputs = model(
                input_ids=input_ids,
                attention_mask=attention_mask,
                labels=labels
            )

            loss = outputs.loss
            logits = outputs.logits

            preds = torch.argmax(logits, dim=1)
            acc = (preds == labels).float().mean().item()

            val_loss += loss.item()
            val_acc_list.append(acc)

    avg_val_loss = val_loss / len(val_loader)
    avg_val_acc = sum(val_acc_list) / len(val_acc_list)

    return avg_val_loss, avg_val_acc

import torch
import os
from transformers import AutoModelForSequenceClassification
from torch.optim import AdamW
from tqdm import tqdm

num_labels = 8
epochs = 6
best_acc = 0.0
save_dir = "/content/drive/MyDrive/Thesis/Code/text_classifier/bert"

os.makedirs(save_dir, exist_ok=True)

# model = AutoModelForSequenceClassification.from_pretrained(
#     "mental/mental-bert-base-uncased",
#     num_labels=num_labels,
#     ignore_mismatched_sizes=True
# )

optimizer = AdamW(model.parameters(), lr=2e-5)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
if torch.cuda.device_count() > 1:
    print(f"Using {torch.cuda.device_count()} GPUs for training!")
    model = torch.nn.DataParallel(model)

model.to(device)

best_val_acc = 0.0

for epoch in range(epochs):
    model.train()
    total_loss = 0.0
    acc_list = []

    for batch in tqdm(train_loader, desc=f"Epoch {epoch+1}/{epochs}"):
        optimizer.zero_grad()

        input_ids = batch['input_ids'].to(device)
        attention_mask = batch['attention_mask'].to(device)
        labels = batch['labels'].to(device)

        outputs = model(
            input_ids=input_ids,
            attention_mask=attention_mask,
            labels=labels
        )

        loss = outputs.loss
        logits = outputs.logits

        preds = torch.argmax(logits, dim=1)
        acc = (preds == labels).float().mean().item()
        acc_list.append(acc)

        loss.backward()
        optimizer.step()

        total_loss += loss.item()

    avg_train_loss = total_loss / len(train_loader)
    avg_train_acc = sum(acc_list) / len(acc_list)

    # ===== VALIDATION =====
    val_loss, val_acc = evaluate(model, val_loader, device)

    print(
        f"Epoch {epoch+1}/{epochs} | "
        f"Train Loss: {avg_train_loss:.4f}, Train Acc: {avg_train_acc:.4f} | "
        f"Val Loss: {val_loss:.4f}, Val Acc: {val_acc:.4f}"
    )

    if val_acc > best_val_acc:
        best_val_acc = val_acc
        print(f"Saving best model (Val Acc={best_val_acc:.4f})")

        if isinstance(model, torch.nn.DataParallel):
            model.module.save_pretrained(save_dir)
        else:
            model.save_pretrained(save_dir)

# ===== VALIDATION =====
val_loss, val_acc = evaluate(model, val_loader, device)

print(
    f"Epoch {epoch+1}/{epochs} | "
    f"Train Loss: {avg_train_loss:.4f}, Train Acc: {avg_train_acc:.4f} | "
    f"Val Loss: {val_loss:.4f}, Val Acc: {val_acc:.4f}"
)

if val_acc > best_val_acc:
    best_val_acc = val_acc
    print(f"Saving best model (Val Acc={best_val_acc:.4f})")

    if isinstance(model, torch.nn.DataParallel):
        model.module.save_pretrained(save_dir)
    else:
        model.save_pretrained(save_dir)

# version of lib
import torch
print(torch.__version__)

label2id = {label: idx for idx, label in enumerate(label_encoder.categories_[0])}
id2label = {idx: label for label, idx in label2id.items()}
import json

with open("label2id.json", "w") as f:
    json.dump(label2id, f, indent=2)

with open("id2label.json", "w") as f:
    json.dump(id2label, f, indent=2)