"""Llama-Guard-3 native taxonomy and mapping to GuardChat categories.

Llama-Guard-3-8B is fine-tuned on Meta's MLCommons-aligned hazard
taxonomy (`S1`-`S14`). GuardChat uses six broader NSFW categories
(:data:`src.utils.CATEGORIES`). To produce a multi-label vector in the
GuardChat format from a Llama-Guard response, we apply the deterministic
mapping below.

The mapping is opinionated:

* ``S1 - Violent Crimes`` and ``S9 - Indiscriminate Weapons`` map to
  ``violence`` (and not ``illegal``) because the GuardChat ``violence``
  category targets graphic / physical-harm content, while ``illegal``
  is reserved for criminal activity that is not inherently violent.

* ``S5 - Defamation`` and ``S10 - Hate`` map to ``harassment``, the
  closest GuardChat category for personally targeted abuse.

* ``S11 - Suicide & Self-Harm`` maps to ``self-harm``.

* ``S3 - Sex-Related Crimes``, ``S4 - Child Sexual Exploitation``, and
  ``S12 - Sexual Content`` all map to ``sexual``.

* The Llama-Guard taxonomy has no analogue for GuardChat's
  ``shocking`` (gore / body-horror / disturbing imagery) category, so
  the native mode never predicts ``shocking``. Use ``mode='custom'``
  in :class:`RecognitionPipeline` to instead pass GuardChat's six
  categories directly into the chat template - the model then reasons
  zero-shot over them and can fire on ``shocking``, at the cost of
  weaker accuracy on the natively-trained classes.
"""

from __future__ import annotations

from typing import Dict, List, Mapping, Sequence, Tuple

from src.utils import CATEGORIES, NUM_CATEGORIES


# Display name for each Llama-Guard 3 category code.
LLAMAGUARD3_CATEGORIES: Dict[str, str] = {
    "S1": "Violent Crimes",
    "S2": "Non-Violent Crimes",
    "S3": "Sex-Related Crimes",
    "S4": "Child Sexual Exploitation",
    "S5": "Defamation",
    "S6": "Specialized Advice",
    "S7": "Privacy",
    "S8": "Intellectual Property",
    "S9": "Indiscriminate Weapons",
    "S10": "Hate",
    "S11": "Suicide & Self-Harm",
    "S12": "Sexual Content",
    "S13": "Elections",
    "S14": "Code Interpreter Abuse",
}


# S-code -> GuardChat category. See the module docstring for the
# rationale behind each individual mapping.
SCODE_TO_GUARDCHAT: Dict[str, str] = {
    "S1": "violence",
    "S2": "illegal",
    "S3": "sexual",
    "S4": "sexual",
    "S5": "harassment",
    "S6": "illegal",
    "S7": "illegal",
    "S8": "illegal",
    "S9": "violence",
    "S10": "harassment",
    "S11": "self-harm",
    "S12": "sexual",
    "S13": "illegal",
    "S14": "illegal",
}


# GuardChat category -> ordered list of plausible S-codes (purely
# informational; the inverse mapping helps generate a custom-taxonomy
# prompt that uses GuardChat names directly).
GUARDCHAT_TO_SCODES: Dict[str, List[str]] = {
    "sexual": ["S3", "S4", "S12"],
    "illegal": ["S2", "S6", "S7", "S8", "S13", "S14"],
    "shocking": [],
    "violence": ["S1", "S9"],
    "self-harm": ["S11"],
    "harassment": ["S5", "S10"],
}


_CATEGORY_INDEX: Dict[str, int] = {c: i for i, c in enumerate(CATEGORIES)}


def parse_llamaguard_response(response: str) -> Tuple[bool, List[str]]:
    """Parse the raw text generated by Llama-Guard-3.

    The expected outputs are::

        "\\n\\nsafe"

    or::

        "\\n\\nunsafe\\nS3"
        "\\n\\nunsafe\\nS1,S11"

    Returns ``(is_unsafe, [S-code, ...])``. Unrecognised responses are
    treated conservatively as ``(False, [])`` (i.e. safe), matching the
    behaviour of Meta's reference implementation.
    """
    if not response:
        return False, []
    s = response.strip().lower()
    if s.startswith("safe"):
        return False, []
    if not s.startswith("unsafe"):
        # Llama-Guard occasionally adds explanatory tokens before the
        # verdict. Look for the first "safe"/"unsafe" anywhere.
        if "unsafe" not in s:
            return False, []

    # Collect any "S<digit>" tokens that appear after the verdict.
    import re
    codes = re.findall(r"S\d{1,2}", response.upper())
    # Deduplicate while preserving order.
    seen = set()
    ordered: List[str] = []
    for c in codes:
        if c not in seen and c in LLAMAGUARD3_CATEGORIES:
            seen.add(c)
            ordered.append(c)
    return True, ordered


def scodes_to_guardchat_vector(
    codes: Sequence[str],
    scode_map: Mapping[str, str] = SCODE_TO_GUARDCHAT,
) -> List[int]:
    """Convert a list of S-codes into a 6-dim GuardChat label vector."""
    vec = [0] * NUM_CATEGORIES
    for c in codes:
        cat = scode_map.get(c.upper())
        if cat is None:
            continue
        idx = _CATEGORY_INDEX.get(cat)
        if idx is not None:
            vec[idx] = 1
    return vec


# Compact, model-friendly description of each GuardChat category, used
# by ``mode='custom'`` to override Llama-Guard's native taxonomy at
# inference time. Phrasing borrows from Appendix A of the paper.
GUARDCHAT_CUSTOM_CATEGORIES: Dict[str, str] = {
    "S1": (
        "Sexual: Content that depicts or implies explicit sexual acts, "
        "nudity, or sexually suggestive scenarios, including exploitative "
        "or non-consensual situations."
    ),
    "S2": (
        "Illegal: Content that promotes, depicts, or provides actionable "
        "guidance for illegal or unlawful activities, including criminal "
        "behavior."
    ),
    "S3": (
        "Shocking: Content intended to elicit strong disgust or distress, "
        "including grotesque, disturbing, or psychologically unsettling "
        "elements such as body horror or decay."
    ),
    "S4": (
        "Violence: Content involving physical harm, injury, or death, "
        "including depictions of violent actions such as assault, torture, "
        "or killing."
    ),
    "S5": (
        "Self-harm: Content that encourages, depicts, or normalizes "
        "self-injury, suicidal behavior, or other forms of self-directed "
        "harm."
    ),
    "S6": (
        "Harassment: Content that targets individuals or groups with "
        "abusive, threatening, humiliating, or degrading language, "
        "including bullying, hate speech, or discrimination."
    ),
}

# Inverse used by ``mode='custom'`` to map S1-S6 back to GuardChat names.
CUSTOM_SCODE_TO_GUARDCHAT: Dict[str, str] = {
    "S1": "sexual",
    "S2": "illegal",
    "S3": "shocking",
    "S4": "violence",
    "S5": "self-harm",
    "S6": "harassment",
}
